version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logs_backend_network
  backend:
    container_name: logs_backend
    build: ./backend
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    networks:
      - logs_backend_network

  frontend:
    container_name: logs_frontend
    build: ./frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - logs_backend_network

volumes:
  postgres_data:

networks:
  logs_backend_network:
    external: true
